services:
  postgres:
    image: postgres:latest
    container_name: econt-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DATABASE_USER:-admin}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-admin}
      POSTGRES_DB: ${DATABASE_DB:-econt_database}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - default

volumes:
  postgres_data:
    name: econt-postgres-data

networks:
  default:
    name: econt-network